# Generated by Django 5.1.2 on 2025-05-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BatchedAlert",
        ),
    ]
