# Generated by Django 5.1.2 on 2025-05-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usernotificationchannel_channel_name_and_more"),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertdelivery",
            name="notification_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_deliveries",
                to="accounts.usernotificationchannel",
            ),
        ),
        migrations.AlterField(
            model_name="alertdelivery",
            name="recipient",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name="BatchedAlert",
        ),
    ]
