# Generated by Django 5.1.2 on 2024-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("monitor", "0002_alter_monitor_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_monitor_e90909_idx",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_state_f31470_idx",
        ),
        migrations.RemoveIndex(
            model_name="alertdelivery",
            name="alerts_aler_method_3dcc6c_idx",
        ),
        migrations.RenameField(
            model_name="alert",
            old_name="triggered_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="acknowledged_at",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="state",
        ),
        migrations.RemoveField(
            model_name="alertdelivery",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="alertdelivery",
            name="method",
        ),
        migrations.AddField(
            model_name="alert",
            name="details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("warning", "Warning"),
                    ("info", "Information"),
                ],
                default="warning",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("monitor_down", "Monitor Down"),
                    ("monitor_up", "Monitor Up"),
                    ("availability", "Availability Issue"),
                    ("response_time", "Response Time Threshold"),
                    ("latency_spike", "Latency Spike"),
                    ("ssl_expiring_soon", "SSL Certificate Expiring Soon"),
                    ("ssl_expired", "SSL Certificate Expired"),
                    ("ssl_invalid", "SSL Certificate Invalid"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alertdelivery",
            name="recipient",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="alertdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["monitor", "-created_at"], name="alerts_aler_monitor_8ece91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type"], name="alerts_aler_alert_t_e287ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity"], name="alerts_aler_severit_202179_idx"
            ),
        ),
    ]
