# Generated by Django 5.1.2 on 2025-05-18 14:48

from django.db import migrations

def forward_func(apps, schema_editor):
    AlertDelivery = apps.get_model('alerts', 'AlertDelivery')
    UserNotificationChannel = apps.get_model('accounts', 'UserNotificationChannel')
    
    for delivery in AlertDelivery.objects.select_related('alert__monitor__user').filter(notification_channel__isnull=True):
        # For email deliveries
        channel = UserNotificationChannel.objects.filter(
            user=delivery.alert.monitor.user,
            channel='email'
        ).first()
        
        if channel:
            delivery.notification_channel = channel
            delivery.save()
        else:
            # Create a default email channel if none exists
            channel = UserNotificationChannel.objects.create(
                user=delivery.alert.monitor.user,
                channel='email',
                enabled=True
            )
            delivery.notification_channel = channel
            delivery.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alertdelivery_notification_channel_and_more"),
    ]

    operations = []
