# Generated by Django 5.1.2 on 2025-05-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usernotificationchannel_channel_name_and_more"),
        ("alerts", "0003_populate_notification_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertdelivery",
            name="notification_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_deliveries",
                to="accounts.usernotificationchannel",
            ),
        ),
    ]
