# Generated by Django 5.1.2 on 2025-05-18 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_usernotificationchannel_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationchannel",
            name="channel_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usernotificationchannel",
            name="connected_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usernotificationchannel",
            name="workspace_icon",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="usernotificationchannel",
            name="workspace_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
