# Generated by Django 5.1.2 on 2025-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usernotificationchannel_channel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationchannel",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
