version: '3.11'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  
  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
  
  celerybeat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db
  
  redis:
    image: redis:7-alpine
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
