# Generated by Django 5.1.2 on 2025-04-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("builder", "Builder"),
                            ("pro", "Pro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "polar_product_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("max_monitors", models.IntegerField()),
                (
                    "check_interval",
                    models.IntegerField(help_text="Check interval in minutes"),
                ),
                ("allowed_notification_channels", models.JSONField(default=list)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("polar_subscription_id", models.CharField(max_length=255, null=True)),
                ("polar_customer_id", models.CharField(max_length=255, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
