# Generated by Django 5.1.2 on 2025-04-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("too_expensive", "Too expensive"),
                            ("not_using", "Not using enough"),
                            ("missing_features", "Missing features"),
                            ("technical_issues", "Technical issues"),
                            ("switching_service", "Switching to another service"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_reason",
                        to="subscriptions.usersubscription",
                    ),
                ),
            ],
        ),
    ]
