# Generated by Django 5.1.2 on 2025-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_cancellationreason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="polar_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="polar_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
