# Generated by Django 5.1.2 on 2024-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for the monitor",
                max_length=255,
                unique=True,
            ),
        ),
    ]
