# Generated by Django 5.1.2 on 2025-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.IntegerField(
                choices=[
                    (1, "1 minute"),
                    (5, "5 minutes"),
                    (10, "10 minutes"),
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (60, "60 minutes"),
                ],
                default=5,
                help_text="Monitoring interval in minutes",
            ),
        ),
    ]
