# Generated by Django 5.1.2 on 2024-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_remove_monitor_custom_interval_monitor_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="is_online",
        ),
        migrations.AddField(
            model_name="monitor",
            name="availability",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Current availability status of the monitored service.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive failed checks."
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether monitoring is active or paused."
            ),
        ),
    ]
