# Generated by Django 5.1.2 on 2024-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_monitor_ssl_expiry_date_monitor_ssl_issuer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="ssl_issuer",
            field=models.JSONField(
                blank=True, help_text="SSL certificate issuer details", null=True
            ),
        ),
    ]
