# Generated by Django 5.1.2 on 2024-12-07 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_remove_monitor_is_online_monitor_availability_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="host",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="port",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="protocol",
        ),
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.IntegerField(
                choices=[
                    (5, "5 minutes"),
                    (10, "10 minutes"),
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (60, "60 minutes"),
                ],
                default=5,
                help_text="Monitoring interval in minutes",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                ],
                default="GET",
                help_text="HTTP method",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="url",
            field=models.URLField(
                default=django.utils.timezone.now,
                help_text="URL to monitor",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
