# Generated by Django 5.1.2 on 2024-12-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_monitor_last_ssl_check_alter_monitorlog_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="method",
        ),
    ]
