# Generated by Django 5.1.2 on 2025-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("monitor_down", "Monitor Down"),
                    ("monitor_up", "Monitor Up"),
                    ("ssl_expiring_soon", "SSL Certificate Expiring Soon"),
                    ("ssl_expired", "SSL Certificate Expired"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
