# Generated by Django 5.1.2 on 2024-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("availability", "Availability"),
                    ("response_time", "Response Time"),
                    ("ssl_expiry", "SSL Expiry"),
                    ("monitor_down", "Monitor Down"),
                    ("monitor_up", "Monitor Up"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
