# Generated by Django 5.1.2 on 2024-12-11 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_remove_monitor_method"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_notific_f2898f_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_9edb86_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("monitor_down", "Monitor Down"),
                    ("monitor_up", "Monitor Up"),
                    ("ssl_expiring", "SSL Certificate Expiring"),
                    ("response_time", "Response Time Alert"),
                    ("system", "System Notification"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="info",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_f2ad08_idx",
            ),
        ),
    ]
